#sb-generated

services:
  web:
    environment:
      -  ASSETS_FRONTEND_BUILD=npm ci --no-audit --no-fund && npm run production
      -  ASSETS_FRONTEND_BUILD_NO_PACKAGE_INSTALL=npm run production
      -  ASSETS_FRONTEND_WATCH=npm ci --no-audit --no-fund && npm run dev-server
      -  ASSETS_FRONTEND_WATCH_NO_PACKAGE_INSTALL=npm run dev-server
      -  ASSETS_FRONTEND_BUILD_DEPLOY=.ddev/commands/web/front.sb.sh build
