#sb-generated

services:
  web:
    environment:
      - AGENT_INSTALL_USER=${AGENT_INSTALL_USER}
      - AGENT_INSTALL_PASS=${AGENT_INSTALL_PASS}
      - AGENT_AI_TOOL=${AGENT_AI_TOOL}
      - JIRA_URL=${AGENT_JIRA_URL}
      - JIRA_USERNAME=${AGENT_JIRA_USERNAME}
      - JIRA_API_TOKEN=${AGENT_JIRA_API_TOKEN}